font:
  normal:
    family: "Iosevka Slab"
  bold:
    family: "Iosevka Slab"
  italic:
    family: "Iosevka Slab"

window:
  padding:
    x: 20
    y: 20
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xffffff'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xcc0000'
    green:   '0x4e9a06'
    yellow:  '0xc4a000'
    blue:    '0x3465a4'
    magenta: '0x75507b'
    cyan:    '0x06989a'
    white:   '0xd3d7cf'

  # Bright colors
  bright:
    black:   '0x555753'
    red:     '0xef2929'
    green:   '0x8ae234'
    yellow:  '0xfce94f'
    blue:    '0x729fcf'
    magenta: '0xad7fa8'
    cyan:    '0x34e2e2'
    white:   '0xeeeeec'
